spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/data/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2